(function () {
  var x = window.CCAF_MOCKS, q = x.q, s = x.scenario;
  x.addPaper(3, 'Evidence and reliability', 'A third paper emphasizing multi-agent evidence, codebase context, CI decisions, and support transcript analysis.', [
    s('research', 'Urban heat evidence review', 'A regional planning office asks a coordinator agent to compare urban-heat interventions. Search, document, and synthesis agents draw from reports with different years and methodologies. The final brief must distinguish supported findings from gaps.', [
      q('1.1', 'A search tool returns three studies and Claude requests another document fetch. Which stop condition should the controller honor?', 'Continue on tool_use and finish only on end_turn|Finish when three sources exist|Finish whenever text accompanies a tool call|Stop after a fixed number of searches as the normal success path', 'A', 'A requested tool call means the application must run the tool and continue. Source count and prose are not protocol-level completion signals.'),
      q('1.2', 'The planning question covers shade and building retrofits but not transit. Which delegation plan avoids wasted work?', 'Assign distinct shade and retrofit scopes, then synthesize|Run every specialist including transit in a fixed order|Let all agents search the same broad phrase|Have synthesis infer transit effects from the shade findings', 'A', 'Scope-specific delegation follows the real question, minimizes duplicated searching, and lets the coordinator combine only relevant findings.'),
      q('1.2', 'The first synthesis ignores maintenance costs. What should the coordinator do?', 'Ask a targeted agent for cost evidence and rerun the synthesis|Publish the brief with no caveat|Rerun every agent identically|Make the cost claim without sources', 'A', 'Adaptive refinement identifies the missing dimension and requests focused evidence instead of repeating the same complete pipeline.'),
      q('1.2', 'Search and document agents disagree about which report is authoritative. Who owns final reconciliation?', 'The coordinator, using source metadata and explicit uncertainty|Whichever agent replied first|A hidden direct conversation between agents|The model with the longest output', 'A', 'The coordinator owns evidence routing, conflict resolution, and the final report; subagents provide bounded findings rather than unreviewed authority.'),
      q('1.3', 'A synthesis subagent receives “cool roofs save 18%” with no source or study year. Which TWO metadata fields are missing?', 'Source location or URL|Publication or collection date|The researcher agent’s preferred writing style|The coordinator’s private transcript|A generic “trust me” label', 'AB', 'Attribution and time are required to assess whether a claim belongs to the right source and period. The subagent cannot infer them from hidden parent context.'),
      q('1.3', 'Three archive queries do not depend on each other. What is the right spawning pattern?', 'Invoke multiple Task calls in one coordinator turn|Wait for the first archive before starting the second|Send all queries only to synthesis|Start a new user conversation for each archive', 'A', 'Independent searches should run in parallel. Multiple Task calls in one response avoid unnecessary coordinator round trips.'),
      q('1.6', 'The archive contains unknown report types and links. How should the investigation begin?', 'Map source types and dependencies, then generate subtasks from discoveries|Apply a fixed extraction sequence without inspection|Read only the first report|Write the final conclusion first', 'A', 'Open-ended evidence discovery needs an adaptive plan based on what exists. A fixed pipeline assumes structure not yet established.'),
      q('2.1', 'Two tools both claim to “analyze sources.” One handles web pages; one handles PDFs. Which description repair is strongest?', 'Specify accepted source types, examples, outputs, and the boundary between tools|Add identical generic descriptions|Remove both tools|Force the PDF tool for all sources', 'A', 'Tool selection improves when the interface explicitly differentiates purpose and formats rather than asking the model to guess.'),
      q('2.2', 'A report server returns HTTP 503 after two retries. Which THREE details should the document agent propagate?', 'Transient access failure|The attempted source and retry count|Any verified partial findings|A successful “no evidence” result|A guessed citation', 'ABC', 'Failure type, attempted recovery, and partial evidence let the coordinator decide whether to seek another source or annotate a coverage gap.'),
      q('2.3', 'A synthesis agent only needs to confirm a citation occasionally. Which tool allocation is safer?', 'Give a narrow verify_citation tool and route broad research through the coordinator|Give it every search, write, and deployment tool|Remove citation checking|Give it unrestricted URL fetching', 'A', 'A constrained cross-role verification tool meets the common need while preserving role boundaries and limiting tool-choice complexity.'),
      q('4.2', 'The brief format varies: sometimes sources appear in prose, sometimes footnotes disappear. What prompt addition best stabilizes output?', 'Two examples that pair claims with citations, including a contested claim|A request to “write professionally”|Only a longer output budget|A self-reported confidence score', 'A', 'Few-shot examples make claim-to-source mapping and contested-value handling concrete, reducing variation that abstract instructions leave open.'),
      q('5.1', 'A 90-page combined input repeatedly loses a key result from the middle. What should be changed?', 'Place a concise key-findings block up front and label detailed sections|Duplicate the whole input unchanged|Drop all source locations|Move the finding deeper into an appendix', 'A', 'A front summary and clear sections reduce position-related omission while retaining detailed evidence for verification.'),
      q('5.3', 'An archive is inaccessible but two other archives were searched successfully. What must the final brief state?', 'Which claims are supported and which coverage is missing due to the inaccessible archive|That no evidence exists anywhere|That every result is equally complete|Only a generic system error', 'A', 'A partial access failure should propagate into coverage annotations, not be silently converted to an empty search result.'),
      q('5.6', 'One source estimates savings for 2030, another reports observed 2022 savings. How should synthesis handle the difference?', 'Keep both values with sources, methods, and timeframes|Average the figures|Choose the newer number automatically|Remove the method descriptions', 'A', 'Forecast and observed data answer different questions. Explicit dates and methods prevent a false contradiction or an unsupported merged estimate.'),
      q('5.5', 'A high-confidence report section contains an unfamiliar building category. Which review policy is prudent?', 'Sample high-confidence findings by category and inspect the new segment|Exempt all high-confidence outputs|Use only the aggregate accuracy figure|Route only low-confidence sentences to review', 'A', 'Stratified sampling finds novel errors in segments that a global confidence score may hide.')
    ]),
    s('dev-productivity', 'Telecom incident code assistant', 'A telecom engineering team uses an agent to trace legacy outage-handling code and propose a narrow fix. The repository has wrapper exports, inconsistent modules, and a strict rule against production writes during investigation.', [
      q('1.1', 'The agent asks for Grep and then receives matching call sites. What must happen before it chooses the next operation?', 'Append the assistant tool request and matching tool result, then ask Claude again|Return the Grep output directly as the final user answer|Discard the result because it is large|Stop whenever a file path appears', 'A', 'The agentic loop needs the tool result in conversation history so the model can reason from the discovered call sites.'),
      q('1.4', 'A proposed “investigation” Bash command would modify production configuration. Which TWO controls should prevent it?', 'A pre-execution mutation policy gate|A read-only tool profile during investigation|A request that the model be polite|A later log review only|A larger max_tokens value', 'AB', 'A read-only capability set and executor gate block the side effect before it happens. A prompt or audit after execution cannot guarantee prevention.'),
      q('1.5', 'Service logs use numeric severity codes while issue records use text. What is the appropriate deterministic hook?', 'Normalize result severity fields in PostToolUse|Change only the final explanation|Have the model infer code meanings from memory|Delete the logs', 'A', 'A post-tool transformation gives the model consistent values before it correlates incidents and source changes.'),
      q('1.6', 'The engineer asks for tests around an outage path whose dependencies are unknown. What task plan is strongest?', 'Trace the entry point, map dependencies, then prioritize tests and adapt as findings emerge|Write twenty tests in alphabetical file order|Ask every subagent to edit the same test file|Run deployment first to see what fails', 'A', 'Dependency discovery determines the useful test boundaries; a fixed arbitrary test count ignores the codebase structure.'),
      q('1.7', 'The repo changed after a two-day paused investigation. What should a resumed session receive?', 'A list of changed files and a request to recheck affected earlier findings|Only its old notes|A statement that the code cannot change|A new confidence threshold', 'A', 'Session context can be stale. Targeted change information directs re-analysis without discarding everything that remains valid.'),
      q('2.1', 'The code assistant chooses search_docs for function callers because its description says “find anything.” What first edit helps?', 'Clarify search_docs versus code Grep capabilities and input examples|Add another “find anything” tool|Force search_docs in the system prompt|Remove all tool descriptions', 'A', 'Tool descriptions should define data sources and boundaries. Ambiguous “find anything” language makes misrouting predictable.'),
      q('2.2', 'An internal symbol server denies access, but Grep finds no matches in the repository. Which interpretation is correct?', 'The permission failure and valid empty repository search are separate results|Both prove the symbol does not exist|Both should be retried indefinitely|The permission failure can be hidden as empty success', 'A', 'Access failure is not evidence of absence; a successful local search with no match is. Recovery decisions require preserving the distinction.'),
      q('2.3', 'A research-only agent receives Write, Edit, Bash, and deployment tools, then modifies files while mapping code. What should change?', 'Restrict it to exploration tools and delegate edits to a separate role|Add more write tools|Add a warning in the prompt while retaining write access|Hide the file changes from the coordinator', 'A', 'Least-privilege role separation prevents accidental mutation and reduces irrelevant tool choices during discovery.'),
      q('2.4', 'The team’s service-schema MCP catalog should be visible in all clones, while its token remains private. Which TWO elements fit?', 'Project-scoped .mcp.json configuration|Environment-variable token reference|Literal token committed to source|A personal-only configuration for the shared catalog|A tool description that includes the secret', 'AB', 'The project should version the shared recipe, while environment expansion supplies credentials outside the repository.'),
      q('2.5', 'You know the wrapper module name but not the implementation path. Which tool sequence is sensible?', 'Glob for wrapper paths, Read exports, then Grep exported names|Read the entire repository first|Edit the first similarly named file|Use Write to search strings', 'A', 'Path discovery, reading exports, and content search progressively trace the real call graph without loading unrelated files.'),
      q('3.1', 'Only one engineer’s local Claude Code follows the incident response checklist. The checklist is in that user’s home CLAUDE.md. Why?', 'User-level instructions are not shared through the repository|The checklist is too short|The model ignores all Markdown files|Bash is required to load instructions', 'A', 'Personal CLAUDE.md affects one user. Version-controlled project guidance is required for consistent team use.'),
      q('3.2', 'A codebase map skill produces lengthy exploratory logs. How can it preserve the main conversation budget?', 'Run the skill with context: fork and return a concise finding summary|Inline all logs into root CLAUDE.md|Repeat the same tool calls in the main session|Disable all tool restrictions', 'A', 'A forked skill isolates verbose exploration while providing the main thread the result it actually needs.'),
      q('3.3', 'Every *IncidentTest.java file needs a special convention, wherever it lives. What configuration fits?', 'A .claude/rules/ path glob matching that filename shape|One CLAUDE.md in a single package|A user-only command|A global prompt pasted manually per task', 'A', 'A glob rule follows matching files across directories, unlike a directory-specific instruction.'),
      q('3.4', 'The outage fix is a two-line guard and the failing test points to the method. What is proportionate?', 'Direct edit, then run the targeted test|Plan a repository-wide migration first|Spawn every specialist|Rewrite the entire module before checking the guard', 'A', 'A bounded, well-evidenced fix does not need a broad planning phase; targeted verification is the useful next step.'),
      q('5.4', 'Long exploration causes the agent to substitute “typical telecom architecture” for observed modules. What should be kept?', 'A scratchpad with actual paths, exports, and confirmed relationships|Only more raw logs in context|A generic architecture template|A larger context window without preserving file evidence', 'A', 'Structured notes preserve verified findings across context limits and prevent plausible but ungrounded claims.')
    ]),
    s('ci', 'Payment-service PR gate', 'A payment team runs Claude Code on pull requests to review changed code and suggest missing tests. The pipeline must be unattended, produce structured findings, and avoid noisy comments. A separate instance reviews generated fixes.', [
      q('1.7', 'The review job resumes yesterday’s session after a rebased PR. Which state action is necessary?', 'Refresh changed files and diff positions before commenting|Trust old line numbers|Assume the previous review is always current|Remove prior findings entirely', 'A', 'A rebase can invalidate line positions and tool results. The reviewer needs the new revision and targeted re-analysis.'),
      q('2.5', 'The agent needs to locate all uses of a renamed authorization function, including re-exports. Which search pattern fits?', 'Grep all names found through wrapper exports, then Read callers|Glob only for *.md files|Write a new function first|Search only the old definition file', 'A', 'Re-exported names require tracing aliases and searching their callers, not stopping at one definition.'),
      q('3.1', 'CI-invoked Claude misses the repository’s available test fixtures. What shared context should be updated?', 'Project CLAUDE.md with fixture locations and testing standards|One developer’s personal notes|The terminal title|A one-off chat that CI cannot access', 'A', 'Version-controlled project instructions give CI the same standards and fixture map as the team.'),
      q('3.2', 'A team-wide /triage-review command must ship with the repository. Which location is correct?', '.claude/commands/ in the repo|~/.claude/commands/ for one user|A JSON array in package.json|A compiled source file', 'A', 'Project commands are shared by version control. Personal commands are not available to all developers or CI.'),
      q('3.3', 'Security review conventions should load for every *.security.test.ts file but not ordinary source. Which rule design fits?', 'A .claude/rules/ file with a matching paths glob|The root CLAUDE.md with no scoping|A manual reminder before every run|A CI variable containing the whole rule', 'A', 'Path-scoped rules load only for files matching the pattern, reducing irrelevant context and inconsistent manual reminders.'),
      q('3.4', 'A change reorganizes authentication across five services with multiple valid boundaries. Which mode should precede edits?', 'Plan mode to map dependencies and compare designs|Direct edit of the first service without exploration|A global search-and-replace|An unreviewed merge', 'A', 'The explicit architectural tradeoff and multi-service scope justify deliberate discovery before implementation.'),
      q('3.5', 'A generated test misses a race involving two concurrent refunds. Which TWO prompts provide useful corrective evidence?', 'A minimal concurrent failing case|The expected invariant after both operations|“Try harder next time”|A confidence score alone|An unrelated style guide', 'AB', 'A reproducible race and expected invariant define the missing behavior, allowing targeted iteration and validation.'),
      q('3.5', 'Claude produces a migration that handles common records but not null timestamps. What is the best next message?', 'Supply a null-timestamp input and expected output as a test case|Ask for prettier code|Increase the task name length|Delete the old tests', 'A', 'A concrete failing example makes the edge case explicit and tests whether the next revision actually fixes it.'),
      q('3.6', 'The PR job stalls waiting for user input. What CLI mode is required for unattended execution?', 'claude -p with a bounded prompt|Interactive chat mode|A longer CI timeout without changing the invocation mode|A manual approval typed for each run', 'A', 'Print mode is non-interactive and suitable for CI. Interactive mode can hang an unattended workflow.'),
      q('3.6', 'Findings must become inline PR comments without parsing prose. Which output contract helps?', 'JSON output plus a schema for file, line, severity, and finding|A free-form paragraph|Only a colored terminal log|A plain-text report parsed with regular expressions', 'A', 'Machine-readable fields give automation an explicit contract, reducing brittle text parsing and misplaced comments.'),
      q('4.1', 'The reviewer flags harmless naming differences, drowning out real defects. Which criterion is useful?', 'Report only behavioral, security, or testable contract violations with evidence|Be “very conservative” with no categories|Increase comment count|Classify every difference as high severity', 'A', 'Specific reportable categories suppress a known false-positive class. Vague caution language does not define the boundary.'),
      q('4.1', 'Reviewers disagree on severity for missing authorization. Which TWO prompt elements make the classification more consistent?', 'Severity rules tied to concrete impact|Examples of low- and high-impact authorization defects|A rule to give every warning the same severity|A longer response budget without criteria|A default of medium severity', 'AB', 'Impact-based criteria and contrasting examples define a reproducible boundary; a blanket default cannot reflect different blast radii.'),
      q('4.2', 'The team wants a stable finding format with a suggested fix and evidence. Which input is strongest?', 'Two or three formatted examples including a no-finding case|“Please be helpful”|A larger token budget|Only the desired field names without examples', 'A', 'Few-shot examples demonstrate both structure and when not to report, improving consistency beyond a field list alone.'),
      q('4.6', 'The same Claude session generates and reviews a security fix. What independent step is preferable?', 'A fresh reviewer session with the diff and tests but no generator reasoning|A longer self-review by the same generating session|No review because tests pass|A larger output length', 'A', 'An independent reviewer is less anchored to its own generation decisions and can inspect the actual artifact more critically.'),
      q('4.6', 'A huge PR has local issues and an interaction between two services. Which TWO review passes preserve coverage?', 'Per-file local analysis|Cross-file integration analysis|One giant free-form pass only|A style-only pass|No pass if CI is green', 'AB', 'Focused local review catches file-level defects; a separate integration pass examines service interactions and data flow.')
    ]),
    s('support', 'Hotel service and transcript analytics', 'A hotel platform has an agent for reservation changes and a nightly pipeline that extracts incident types from support transcripts. The live agent can propose credits but requires verified identity and policy compliance. Analysts use the nightly data to improve service.', [
      q('1.1', 'A live agent returns both apology text and a tool_use request for reservation lookup. What should the app do?', 'Run the lookup and continue the model loop|Treat the apology as final|Wait for the next customer turn|Close the case because text exists', 'A', 'A tool request is the protocol signal to execute and return a tool result. Text beside it does not mean the task is complete.'),
      q('1.4', 'A credit operation must not run until the reservation is tied to a verified account. What design guarantees this?', 'An executor prerequisite that blocks the credit tool|A polite prompt asking for verification|A few examples with the right order|A larger context window without targeted change details', 'A', 'Financial prerequisites require deterministic enforcement at the tool boundary, not probabilistic instruction following.'),
      q('1.5', 'One booking tool returns room status codes while another returns named states. Which hook use is appropriate?', 'Normalize both result types before the agent reasons|Rewrite only the final customer message|Ask the customer to translate codes|Ignore the mismatch', 'A', 'A result-normalization hook gives the model consistent status semantics before it makes a credit or handoff decision.'),
      q('2.1', 'Tools change_reservation and propose_credit have short, overlapping descriptions. What should be added first?', 'Clear purpose, accepted IDs, effects, and examples of when not to use each|A shared one-word description|More unrelated tools|A forced call to both on every turn', 'A', 'Descriptions are the primary selection signal, so effects and boundaries must be explicit before adding a routing layer.'),
      q('2.4', 'Analysts need a discoverable list of transcript categories before extracting them. Which MCP capability fits?', 'A resource exposing the category catalog|One exploratory tool call per category|A secret in the prompt|An action that edits production bookings', 'A', 'MCP resources expose reference catalogs for discovery without repeated exploratory tool calls.'),
      q('4.3', 'The nightly classifier must return one of several structured incident types, but the type is initially unknown. Which mode fits?', 'tool_choice any across schema tools|tool_choice auto with free-form text allowed|Force a single unrelated type|No schema validation', 'A', 'any requires a tool call while allowing selection among type-specific schemas; auto can instead yield unstructured text.'),
      q('4.3', 'A transcript has no stated refund amount. What should the output contract permit?', 'A null or absent amount with an explicit evidence state|A required guessed amount|A default amount equal to room price|Removal of all structured fields', 'A', 'The schema should represent missing source facts rather than encourage fabricated monetary values.'),
      q('4.4', 'The model labels a transcript “staff rude” but cites a line about a booking-system outage. What validation feedback should retry include?', 'The specific unsupported label and cited line mismatch|Only “wrong answer”|The same prompt unchanged|A generic retry instruction with no failed-line evidence', 'A', 'Targeted error feedback points to the semantic mismatch and lets a retry correct it against the original evidence.'),
      q('4.4', 'A transcript is truncated before the customer’s outcome. Why is repeated extraction insufficient?', 'The necessary evidence is missing; request the full transcript or mark unknown|Retry the same truncated transcript with stronger completion instructions|The output schema is too strict|The batch ID should be removed', 'A', 'No amount of identical retrying can recover unprovided conversation content. The correct state is missing evidence or an upstream retrieval fix.'),
      q('4.5', 'Weekly transcript reports can arrive by the following morning. What processing path is economical?', 'Batch independent transcripts and correlate by custom_id|Block the live booking agent on the whole batch|Use batch to run an interactive multi-turn tool loop|Send all transcripts as one unbounded request', 'A', 'Latency-tolerant independent work fits batch processing, while custom_id preserves record identity through asynchronous results.'),
      q('4.5', 'A batch completes with only 27 failed transcripts. Which TWO recovery steps make sense?', 'Resubmit those 27 by custom_id|Modify over-limit transcripts before retry|Resubmit the entire successful batch|Treat failures as “no issue”|Reconcile responses by submission order instead of custom_id', 'AB', 'Targeted resubmission avoids duplicate work, and context-limit failures need a smaller or chunked input rather than the same request.'),
      q('5.1', 'A long live chat summary drops a promised $25 credit and checkout date. What should be persisted?', 'Exact transactional facts in a separate case record|Only the customer’s mood|All raw model reasoning forever|A generic “credit discussed” note', 'A', 'A structured facts layer protects exact amounts and dates from lossy conversation summarization.'),
      q('5.2', 'A customer asks for a manager about an accessibility request not covered by policy. Which TWO facts independently warrant escalation?', 'The explicit request for a person|The documented policy gap|The customer’s message length|A low model confidence number alone|The existence of an active booking', 'AB', 'A stated human preference and a real policy gap are each escalation triggers. Message length and self-reported confidence are unreliable substitutes.'),
      q('5.2', 'Two guests with the same name have active bookings. Which next action is safe?', 'Ask for a booking-specific identifier before any credit|Select the newest booking|Credit both bookings|Choose based on sentiment', 'A', 'Ambiguous identity requires clarification; heuristics would risk acting on the wrong reservation.'),
      q('5.3', 'Transcript retrieval times out for one hotel but returns no matches for another. How should the analyst agent describe them?', 'One access failure and one valid empty result|Two successful empty results|Two permanent policy denials|One fabricated incident each', 'A', 'The two outcomes have different evidence and recovery implications. A timeout does not show that no transcript exists.')
    ])
  ]);
})();
