(function () {
  var x = window.CCAF_MOCKS, q = x.q, s = x.scenario;
  x.addPaper(1, 'Production judgment', 'A broad first paper spanning support automation, research, CI review, and document extraction.', [
    s('support', 'Retail resolution desk', 'A retailer is piloting a Claude-based resolution agent for order problems. It can read customer and order records, issue low-value credits, and prepare human handoffs. Incorrect account selection and unsupported refunds are high-impact failures.', [
      q('1.1', 'A customer asks about a missing parcel. Claude returns a tool_use block for lookup_order plus a short sentence. What should the controller do next?', 'Show the sentence and close the turn|Execute the requested tool, append its result, and call Claude again|Wait for a second user message before running the tool|Treat the sentence as proof the answer is complete', 'B', 'tool_use ends the current model response, not the user task. The application executes the client tool and returns a matching tool_result for another model turn.'),
      q('1.1', 'A controller stops after five iterations although the fifth response requests another needed lookup. Which change best preserves correct completion?', 'Use end_turn as the success signal and keep a separate safety budget|Stop whenever assistant text is present|Force exactly five tool calls for every request|Parse “I am done” from Claude prose', 'A', 'A safety cap protects against runaway loops but cannot define task completion. The controller should finish on end_turn and handle budget exhaustion as an exception.'),
      q('1.4', 'Audit logs show the agent sometimes issues a credit before verifying the account. Which control is reliable enough for this financial prerequisite?', 'A stronger reminder in the system prompt|A few examples of the right sequence|An executor gate that rejects credit calls without a verified customer ID|A separate sentiment classifier', 'C', 'A deterministic executor gate blocks the side effect regardless of the model’s chosen sequence. Prompt guidance can help but cannot guarantee compliance.'),
      q('1.4', 'The agent must hand a disputed-charge case to staff who cannot see the chat transcript. Which TWO fields are essential in the handoff?', 'Verified customer and order identifiers|A verbatim copy of every tool payload|Evidence, root cause, and recommended next action|Only the model’s confidence number|A generic “please investigate” note', 'AC', 'A useful handoff carries identity and a concise evidence-backed recommendation. Raw payload dumps and confidence numbers do not give staff an actionable case.'),
      q('1.5', 'Two tools return dates in Unix seconds and ISO 8601. The agent repeatedly compares them incorrectly. Where should normalization happen?', 'In a PostToolUse result transformation before Claude reasons over the values|Only in the final customer response|In a new unrelated subagent|By asking the customer to convert dates', 'A', 'Normalizing tool results at the boundary makes later reasoning use one representation. A final-response rewrite cannot repair earlier decisions made from inconsistent dates.'),
      q('1.6', 'A request combines a damaged item and an address correction. The first requires evidence review; the second needs a profile update. What decomposition is best?', 'Treat both as one refund decision|Investigate the two concerns separately, then synthesize one reply|Escalate both without investigating|Always run every available specialist in sequence', 'B', 'The concerns have different evidence and operations. Separate investigation prevents one path from contaminating the other, while a final synthesis keeps the customer response coherent.'),
      q('1.7', 'An investigator resumes a named session after the order-status service changed its response fields overnight. What should the resumed agent receive?', 'Nothing; the old tool result is permanent truth|A targeted note about the changed service plus fresh relevant results|Resume without refreshing any changed tool results|A fixed number of extra turns', 'B', 'Resumption preserves context but can also preserve stale evidence. State the changed boundary and refresh the affected facts rather than trusting yesterday’s tool payload.'),
      q('2.1', 'lookup_order and get_customer both say “look up an identifier.” The agent confuses them. Which first fix is most direct?', 'Differentiate inputs, outputs, examples, and boundaries in each tool description|Increase max_tokens|Add ten unrelated tools|Force every request through lookup_order', 'A', 'Tool descriptions are the selection contract. Clear scope and input examples address the ambiguity without an unnecessary router or blanket forced call.'),
      q('2.2', 'A credit tool rejects a request under the nonrefundable policy. Which THREE fields make its response actionable?', 'isError true|errorCategory: business|isRetryable: false|An empty success payload|A retry-after value for the same unchanged request', 'ABC', 'The caller needs an explicit error, a business category, and non-retryable status so it can explain or escalate rather than repeat the prohibited operation.'),
      q('2.3', 'The support agent has 18 tools, including report generation and code editing, and increasingly chooses the wrong one. Which TWO changes fit the failure?', 'Limit the agent to support-relevant tools|Give every tool a shorter, identical description|Use a constrained helper for a frequent cross-role lookup|Add more tools so the model has alternatives|Let the model edit the tool registry at runtime', 'AC', 'A smaller role-specific toolset reduces choice confusion. A narrow helper can cover a real cross-role need without exposing unrelated capabilities.'),
      q('2.4', 'The team needs the same CRM MCP server in every repository clone without committing its token. Where should the shared recipe and secret value go?', 'Recipe in project .mcp.json; token supplied through an environment variable|Token literal in .mcp.json; recipe in a README|Everything in one developer’s user config|Hard-code the token into the tool description', 'A', 'Project configuration is shareable; the secret value is not. Environment-variable expansion lets the team version the integration recipe without versioning credentials.'),
      q('4.2', 'The agent produces inconsistent handoff notes for partial refunds and replacements. What prompt addition most directly teaches the desired structure?', 'Two or three worked handoff examples including an ambiguous case|A vague instruction to be consistent|A larger context window only|A request for the model to grade itself from 1 to 10', 'A', 'Few-shot examples demonstrate both format and decision boundaries. They give the model concrete patterns for unusual cases rather than a general aspiration.'),
      q('5.1', 'After a long conversation, a summary replaces “refund $47.80 by 12 October” with “customer wants compensation.” What must be preserved separately?', 'A structured case-facts block with amount, date, and order ID|Every raw tool payload forever|Only the latest customer mood|The assistant’s original wording only', 'A', 'Transactional values are easy to blur during summarization. A persistent structured facts layer preserves exact amounts and commitments across context compression.'),
      q('5.2', 'A customer explicitly says “I want a person now.” The issue looks simple. What should the agent do?', 'Respect the request and initiate human handoff|Insist on trying automation first|Escalate only if sentiment is negative enough|Ask the model for a confidence score', 'A', 'An explicit human request is an escalation trigger in its own right. Apparent simplicity does not override the customer’s stated preference.'),
      q('5.2', 'A name search returns three plausible accounts. Which TWO actions are appropriate before a credit is issued?', 'Ask for another identifier|Pick the most recent account|Keep financial actions blocked until identity is verified|Choose the record with the nearest address|Hide the ambiguity from the customer', 'AC', 'Multiple matches require clarification and a continued financial gate. Heuristic selection would turn ambiguous identity into a risky side effect.')
    ]),
    s('research', 'Municipal resilience study', 'A city research team uses a coordinator with search, document-analysis, and synthesis specialists to compare flood-mitigation proposals. The final report must cite source pages and distinguish established evidence from disputed estimates.', [
      q('1.1', 'The synthesis agent asks for another source lookup with stop_reason tool_use. Which state transition is correct?', 'Execute the lookup and return the tool_result in conversation history|Publish the draft because text appeared beside the request|Reset the conversation and start over|Mark end_turn because the lookup is optional', 'A', 'The model requested a tool, so the controller must execute it and return its result before asking for another response. Text beside a tool request is not completion.'),
      q('1.2', 'A broad policy question sometimes needs two specialists and sometimes four. How should the coordinator route work?', 'Always invoke all specialists in a fixed order|Choose specialists from the question’s evidence needs, then aggregate their outputs|Let specialists talk directly with no coordinator trace|Give every specialist the entire investigation', 'B', 'Dynamic selection avoids needless calls while retaining one coordinator for decomposition, provenance, errors, and final synthesis.'),
      q('1.2', 'Two search agents repeatedly return the same flood report. Which delegation change addresses the duplication?', 'Assign distinct source types or subtopics with explicit boundaries|Increase both agents’ token limits|Add another identical search agent|Remove all source metadata', 'A', 'Distinct scopes make parallel work complementary. More identical capacity does not solve duplicated ownership of the search space.'),
      q('1.2', 'A synthesis draft omits drainage costs even though the source pool contains them. What should an adaptive coordinator do?', 'Send a targeted follow-up for cost evidence and rerun synthesis|Accept the draft because it is fluent|Restart all agents with the same prompts|Remove the cost requirement', 'A', 'The coordinator should identify the gap, request only the missing evidence, and synthesize again. Repeating the whole pipeline wastes work and may reproduce the same omission.'),
      q('1.3', 'The analyst subagent must evaluate PDFs found by a search subagent. Which TWO details belong in its handoff?', 'Search findings with source URLs and page locations|A statement that it can see the parent transcript|The task goal and quality criteria|Only a short “analyze these” instruction|Unattributed quotations detached from documents', 'AC', 'Subagents do not automatically inherit the parent history. They need explicit evidence with locations plus a self-contained task and acceptance criteria.'),
      q('1.3', 'Three independent archives can be searched simultaneously. What invocation pattern minimizes latency?', 'Emit multiple Task calls in one coordinator response|Call one Task per coordinator turn|Force the synthesis agent to search all archives itself|Wait for the final report before searching', 'A', 'Independent tasks can be launched in parallel by issuing multiple subagent calls together. Sequential turns add avoidable latency.'),
      q('1.5', 'One document tool returns area in acres, another in hectares. Where should the unit conversion occur for reliable comparison?', 'Normalize tool results before the model compares them|Ask synthesis to guess equivalent units|Convert only in the final chart caption|Ignore units and compare the numbers', 'A', 'Boundary normalization prevents the agent from reasoning over heterogeneous units. Fixing the chart after decisions are made is too late.'),
      q('1.6', 'The city asks for an open-ended review of a newly released technical archive. Which approach fits?', 'Map the archive first, then create adaptive subtasks from what is found|Force the same five-step review pipeline regardless of contents|Summarize only the first file|Apply a fixed extraction plan before mapping the archive', 'A', 'Open-ended investigation requires discovering the structure before choosing subtasks. A fixed sequence is better for predictable, known review stages.'),
      q('2.1', 'The model calls generic analyze_content for a PDF when a document-specific extractor exists. What description change helps?', 'Give the extractor clear document formats, outputs, and when to choose it over web analysis|Rename every tool to analyze_content|Hide the PDF extractor from the tool list|Force the extractor on all tasks', 'A', 'Distinct tool descriptions explain capability boundaries. Renaming every tool alike or forcing one tool discards useful model selection.'),
      q('2.2', 'A source search returns zero matches after a successful query. What should the tool report?', 'A successful empty result with query details|A transient timeout error|A permission error|A fabricated source to keep the pipeline moving', 'A', 'No matches is valid data, not an access failure. Preserving that distinction lets the coordinator decide whether to broaden the search.'),
      q('2.3', 'The synthesis specialist needs occasional claim verification but should not browse freely. Which design is proportionate?', 'Give it a narrow verify_claim tool and route larger searches through the coordinator|Give it every search and file tool|Remove verification entirely|Let it call the web with unrestricted URLs', 'A', 'A constrained cross-role tool supports a frequent need without expanding the synthesizer into an uncontrolled researcher.'),
      q('4.1', 'Reviewers want only source-backed contradictions in the report, not style notes. Which instruction is most precise?', 'Report a conflict only when two cited claims refer to the same measure, place, and time; skip style|Be conservative and high confidence|Flag anything that feels inconsistent|Report every wording difference', 'A', 'A categorical condition defines what counts as a real conflict. General caution words do not reliably reduce false-positive categories.'),
      q('5.1', 'A 40-page source packet puts the key budget finding in the middle, where the synthesis repeatedly misses it. Which input design helps?', 'Put a concise key-findings section first and retain labeled detail sections|Duplicate the whole packet three times|Remove page references|Place the finding only in the last appendix', 'A', 'Position and organization matter in long inputs. A front summary plus labeled evidence reduces the lost-in-the-middle risk without discarding provenance.'),
      q('5.3', 'A document-analysis agent times out after extracting two of three reports. Which TWO fields should its error handoff include?', 'The two partial findings and their sources|A false “no documents found” success|The failed source, attempted query, and retry status|Only a generic “failed” string|A request to abandon the entire report', 'AC', 'Structured failure context preserves useful work and tells the coordinator what to retry or replace. An empty success would hide the access failure.'),
      q('5.6', 'Two credible reports give different flood-loss figures, one for 2021 and one for 2024. What should synthesis do?', 'Preserve both figures with sources and collection dates, then explain the temporal difference|Average them without attribution|Choose the larger figure as safer|Drop both because they conflict', 'A', 'A difference in collection period may explain the values. Provenance and dates must survive synthesis before a reconciliation decision is made.')
    ]),
    s('ci', 'Pull-request review pipeline', 'A platform team runs Claude Code during pull requests to review risky changes and propose missing tests. Review findings are posted automatically, so duplicate comments and stylistic false positives quickly erode developer trust.', [
      q('1.7', 'A long review session is resumed after the PR branch was force-pushed. What is the safest next step?', 'Tell the session which files and SHA changed and refresh affected analysis|Reuse prior tool results without checking|Assume the old diff still identifies current lines|Fork the stale result into ten identical sessions', 'A', 'A resumed session may carry obsolete file and line evidence. Give it the new revision and re-read affected areas before posting findings.'),
      q('2.5', 'The review agent knows an error string but not which file contains it. Which built-in tool should it use first?', 'Grep for the text across files|Glob for matching file names only|Write a new source file|Bash deploy the service', 'A', 'Grep finds content patterns. Glob finds paths by name, so it cannot directly locate an error string buried in code.'),
      q('3.1', 'The team’s review standards must follow every repository clone. Where should they live?', 'Version-controlled project CLAUDE.md or scoped rules|One engineer’s ~/.claude/CLAUDE.md|A private chat transcript|The CI log from the prior run', 'A', 'Project guidance is shared through version control. User-level instructions are personal and will not reliably reach teammates or CI.'),
      q('3.1', 'Review output varies between CI and local runs. Which command helps inspect what Claude Code actually loaded?', '/memory|/clear|/cost|/rename', 'A', 'The memory inspection command shows loaded instruction files and helps diagnose configuration hierarchy differences between environments.'),
      q('3.2', 'A verbose dependency audit should run in isolated context so it does not crowd the main review. Which skill setting fits?', 'context: fork in SKILL.md frontmatter|A larger CLAUDE.md file|A user-only command copied into CI logs|A prompt telling Claude to forget the audit', 'A', 'A forked skill receives an isolated working context and returns a result, keeping exploratory output out of the main conversation.'),
      q('3.2', 'A command to check the team’s PR checklist must be available to all developers. Which path is appropriate?', '.claude/commands/ in the repository|~/.claude/commands/ on one laptop|A Markdown comment in the README only|A hidden CI environment variable', 'A', 'Project-scoped commands are version-controlled and shared. A home-directory command is personal and will not ship with the repository.'),
      q('3.3', 'Test files are scattered under many packages but share one review convention. Which configuration loads it only for matching files?', 'A .claude/rules/ file with a **/*.test.ts path pattern|A user-level CLAUDE.md that lists every file|One root instruction telling Claude to guess|A fixed Bash alias', 'A', 'Path-scoped rules match by glob across directories, reducing irrelevant instructions while applying one test convention consistently.'),
      q('3.4', 'A one-line null check has a clear failing test and no architecture choice. Which mode is proportionate?', 'Direct execution with the test as evidence|Plan mode for a week before reading the file|A four-agent research pipeline|A new repository', 'A', 'The change is bounded and evidence already identifies the path. Plan mode is most useful when dependencies and choices require exploration first.'),
      q('3.5', 'The generated review repeatedly misses an edge case involving empty arrays. What input most helps the next iteration?', 'A concrete failing input, expected result, and test assertion|A request to “be smarter”|A longer role description only|A self-rated confidence number', 'A', 'Specific tests make the gap executable and falsifiable. General praise or caution does not define the missing behavior.'),
      q('3.6', 'The CI job hangs because Claude Code asks an interactive question. Which TWO CLI choices support non-interactive machine-readable operation?', 'Use -p / --print|Use --output-format json and a schema when needed|Open plan mode in a terminal tab|Wait for a human to press Enter on every PR|Store the output only as prose in stdout', 'AB', 'Print mode avoids the interactive session, while JSON output with a schema gives CI a parseable contract. Human input would defeat unattended operation.'),
      q('3.6', 'A review rerun posts the same finding after it was fixed in a new commit. What context should the next run include?', 'Prior findings plus the new diff, asking for only new or unresolved issues|The old finding only|A rerun that omits prior finding IDs and resolutions|A larger token limit without history', 'A', 'Prior findings provide deduplication state. The new revision must still be checked so the agent distinguishes fixed, persisting, and novel problems.'),
      q('4.1', 'The review bot floods PRs with harmless local style preferences. Which change best restores precision?', 'Define reportable bug and security categories; suppress style-only comments|Ask for more confidence without criteria|Increase the number of comments|Classify all formatting as critical', 'A', 'Explicit report criteria remove the high-false-positive category. Vague confidence filtering leaves the category definition unresolved.'),
      q('4.2', 'Findings alternate between vague prose and actionable reports. What should the prompt include?', 'Two worked examples with file, location, evidence, severity, and suggested fix|A longer list of adjectives|A request to self-review its own output|Only a maximum word count', 'A', 'Few-shot examples demonstrate the target structure and specificity. They teach the format more reliably than abstract formatting instructions.'),
      q('4.6', 'Claude generated the patch and then declares it correct in the same conversation. What review design is stronger?', 'Use a second independent instance without the generator’s reasoning context|Ask the generator to say “are you sure?”|Increase generation temperature|Skip all tests', 'A', 'Independent review is less anchored to the generation path. The reviewer should inspect the actual diff and tests, not inherit the author’s rationale.'),
      q('4.6', 'A 70-file PR produces locally sensible findings that miss cross-file data flow. Which TWO passes should the pipeline use?', 'Focused per-file reviews|A cross-file integration pass|One enormous unstructured pass only|A style-only pass repeated three times|No review because the change is large', 'AB', 'Local passes reduce attention dilution; a separate integration pass checks relationships that no single file can establish.')
    ]),
    s('extraction', 'Invoice ingestion service', 'A finance team extracts fields from supplier invoices into a ledger. Layouts vary, some invoices omit optional fields, and every extracted total must be reconcilable. Nightly bulk ingestion is allowed, but pre-payment checks are blocking.', [
      q('2.1', 'The model has extract_invoice and summarize_invoice tools with overlapping descriptions. Which change improves selection?', 'State that extract_invoice returns schema fields for ledger use while summarize_invoice produces prose for readers|Remove both descriptions|Use one vague “process invoice” tool|Force summarize_invoice for every input', 'A', 'Distinct outcome and input boundaries tell the model which tool fits ledger extraction versus a human summary.'),
      q('2.4', 'Operators want a catalog of supported invoice formats without making repeated exploratory calls. Which MCP feature fits?', 'Expose a format catalog as an MCP resource|Add a new tool call for every format name|Hide supported formats in a personal prompt|Hard-code one format forever', 'A', 'An MCP resource can expose discoverable reference content such as schemas and catalogs without consuming a tool call for every lookup.'),
      q('2.5', 'A developer needs to find every schema file ending in .json before reading any of them. Which built-in tool is the right first step?', 'Glob with a path pattern|Grep for a field value|Edit the first similarly named file without reading it|Run the extraction job', 'A', 'Glob selects files by path shape. Grep is for content search after candidate files or patterns are known.'),
      q('3.3', 'Invoice parsers live in several directories but all *.schema.json files need the same convention. How should the rule be scoped?', 'A path-glob rule matching **/*.schema.json|A CLAUDE.md in one unrelated directory|A user-only preference|A single prompt pasted into every task', 'A', 'A glob-based rule spans directories by file type and loads only where relevant, rather than relying on one directory hierarchy.'),
      q('3.4', 'A migration changes parsing, validation, and storage across 45 files with several design options. Which approach should start the work?', 'Plan mode to map dependencies and choose a design|Blind direct edits in the first file|A single inline sed command|Immediate deployment before tests', 'A', 'The scope and competing designs justify exploration before mutation. Direct execution is better for a small, already-understood change.'),
      q('3.5', 'Developers disagree on how to handle missing tax IDs. Which TWO inputs most clarify the requirement?', 'Concrete examples of invoices with and without IDs and expected outputs|A test covering the missing-field case|A request for “clean code”|One clean invoice example with no missing-field cases|A longer role description without input/output examples', 'AB', 'Examples and tests turn an ambiguous rule into observable behavior. General style language and sampling settings do not settle field semantics.'),
      q('4.3', 'Invoice types vary, but every response must be a valid structured tool call. Which tool_choice mode guarantees a tool while allowing schema choice?', 'any|auto|none|Force one invoice schema for all documents', 'A', 'any requires a tool call but lets the model choose among available extraction tools. auto may return text instead.'),
      q('4.3', 'A supplier sometimes omits the purchase-order number. Which schema design avoids fabricated values?', 'Make the field nullable or optional with an explicit absent case|Require a nonempty number on every invoice|Ask the model to infer it from the supplier name|Drop validation entirely', 'A', 'When source data can genuinely be absent, the contract must represent absence. A required nonempty field pressures the model to invent one.'),
      q('4.4', 'A schema-valid invoice lists line amounts totaling 98.00 but states 108.00. What should the application do?', 'Run deterministic arithmetic validation and retry or review with the specific mismatch|Assume schema validity proves arithmetic truth|Silently overwrite the stated total|Ignore the discrepancy because JSON parsed', 'A', 'Schema conformance ensures structure, not semantic consistency. A deterministic check surfaces the discrepancy for targeted correction or human review.'),
      q('4.4', 'A required routing number is absent from the source image. The extractor fails twice. Is a third identical retry useful?', 'No; mark absent and request missing source or human review|Yes; retry the same source with stronger wording until a nonempty number appears|Reduce the schema to an empty object|Use the previous wrong value', 'A', 'Retries cannot recover information not present in the provided evidence. The correct path is explicit absence or acquisition of the missing document.'),
      q('4.5', 'Five thousand invoices can complete overnight; no user waits for each result. Which API path is cost-aligned?', 'Message Batches API with custom_id correlation|Synchronous calls blocking one UI request|A multi-turn tool loop inside each batch request|A forced high-priority real-time queue', 'A', 'Batching fits latency-tolerant independent extraction and custom_id ties results to documents. It is not a mid-request tool-execution loop.'),
      q('4.5', 'A payment approval must finish before the user clicks Confirm. Which TWO reasons rule out Batch API as the only path?', 'There is no guaranteed low-latency SLA|A batch request cannot run a multi-turn client-tool loop inside one request|Batch responses are always invalid JSON|Batch cannot correlate results|Batch requires a human on every item', 'AB', 'The blocking latency requirement conflicts with batch timing, and batch requests cannot pause for client tools and resume within the same request.'),
      q('5.3', 'An OCR subagent times out on page 4 after extracting pages 1–3. Which error is useful to the coordinator?', 'Transient timeout with page number, partial fields, and retry attempt|Successful empty document|“Failed” with no page detail|A guessed page 4 result', 'A', 'Structured partial results let the coordinator retry only the failed page and retain supported fields. Empty success would hide the access failure.'),
      q('5.4', 'After inspecting hundreds of parser files, the agent cites typical patterns instead of the classes it previously found. What should it preserve?', 'A scratchpad of verified file paths, relationships, and open questions|Only a longer conversation with raw tool output|A fabricated architecture diagram|No state, because compaction is lossless', 'A', 'A concise external scratchpad anchors later work to observed files. Raw context can degrade or be compacted away.'),
      q('5.5', 'Overall field accuracy is 97%, but handwritten invoices may perform worse. What should be measured before removing human review?', 'Accuracy stratified by document type and field, with sampled high-confidence cases|Only the aggregate number|Only the model’s own confidence scores|Only the fastest invoices', 'A', 'Aggregate accuracy can hide a weak segment. Stratified labeled checks and high-confidence sampling reveal errors before review is reduced.')
    ])
  ]);
})();
