(function () {
  var x = window.CCAF_MOCKS, q = x.q, s = x.scenario;
  x.addPaper(2, 'Architecture under constraints', 'A second paper centered on developer tooling, team configuration, support operations, and claims extraction.', [
    s('dev-productivity', 'Banking codebase assistant', 'A bank is introducing a Claude-powered assistant to explore a large legacy service repository and propose safe tests. The assistant can inspect source, consult an internal schema catalog, and draft changes, but production mutations require a separate gate.', [
      q('1.1', 'The assistant asks to read a controller file and returns stop_reason tool_use. The UI also receives a brief plan sentence. What should the host do?', 'Run Read, append the tool result, and continue the loop|Display the plan as the final answer|Run Write instead because the task is coding|End the session after any text block', 'A', 'tool_use denotes a handoff for client execution. The plan text can coexist with the request; only a later end_turn completes the model turn.'),
      q('1.2', 'A task may involve only Java services or may also require SQL migration analysis. How should the coordinator select specialists?', 'Inspect task needs and invoke only relevant specialists|Always run Java, SQL, security, and docs specialists in sequence|Let each specialist spawn the others without a coordinator|Give the SQL agent final edit authority', 'A', 'Dynamic delegation follows the actual scope, reducing unnecessary calls while the coordinator keeps ownership of integration and evidence.'),
      q('1.3', 'A repository-mapping subagent found the transaction boundary. What must the test-writing subagent receive to use that finding?', 'The exact file paths, boundary summary, and task goal in its prompt|A promise that it can inspect the parent transcript|Only the name of the mapping agent|The coordinator’s hidden context without copying it', 'A', 'Subagent context is isolated. Explicit file references and a self-contained task prevent the next agent from inventing the missing analysis.'),
      q('1.4', 'The assistant proposes deleting a production migration file during a “cleanup” task. Which TWO controls are appropriate?', 'A pre-execution policy gate that rejects the deletion|A prompt-only reminder that production files matter|An allowed-tools restriction for read-only investigation|Automatic deletion after the model gives a reason|A hidden retry loop', 'AC', 'The executor and tool surface can deterministically prevent a prohibited mutation. A prompt reminder alone is not a safe boundary for destructive work.'),
      q('1.5', 'The schema catalog returns column types as vendor-specific numeric codes. What hook behavior helps downstream reasoning?', 'A post-tool normalization that maps codes to clear types|A final answer rewrite after SQL is generated|Asking Claude to infer numeric codes from nearby prose|A rule to ignore column types', 'A', 'Normalizing the tool result before it enters the model context prevents later SQL decisions from relying on opaque codes.'),
      q('1.6', 'The request “add tests for this legacy payment flow” has unknown dependencies. What should happen before generating test files?', 'Map call paths and high-impact branches, then prioritize test subtasks|Write a fixed number of tests in the first file|Ask every subagent to edit the same package|Copy tests from another service without inspection', 'A', 'Open-ended testing work benefits from adaptive decomposition grounded in the actual code path, not a predetermined file count.'),
      q('2.1', 'A tool named analyze_file overlaps with explain_code. Both accept paths. Which description most improves selection?', 'One that states supported file types, output contract, and when to choose it over explain_code|One that says only “analyzes files”|One that lists every tool in the system|One that repeats the tool name without input or output details', 'A', 'A discriminating description supplies the decision boundary. Similar names without output and scope differences invite misrouting.'),
      q('2.2', 'The schema catalog is temporarily unavailable. Which THREE error fields support a measured recovery?', 'isError true|A transient error category|isRetryable true|A successful empty schema|A permanent permission-denied category', 'ABC', 'The structured response must mark failure, classify it as transient, and permit bounded retry. A successful empty schema would falsely imply that no schema exists.'),
      q('2.3', 'The mapping agent needs Grep and Read, while the writing agent needs Edit and tests. What is the right tool allocation?', 'Give each role its needed set and keep production write tools gated|Give both all 18 available tools|Remove Grep and force raw file reads|Let the mapping agent deploy code directly', 'A', 'Role-scoped tools reduce selection errors and privilege. The coordinator can route cross-role needs instead of giving all agents every capability.'),
      q('2.4', 'The internal schema catalog is common to the team, but each developer has a personal scratch MCP server. Which configuration split fits?', 'Project .mcp.json for shared catalog; user-level config for scratch server|Both in a committed file with literal credentials|Both in one teammate’s personal config|No MCP config because resources cannot be shared', 'A', 'Shared integrations belong in project scope with secret references; personal experiments belong in user scope. This separates reproducibility from private settings.'),
      q('2.5', 'A developer asks for files named *Repository.java, then callers of one selected class. Which TWO search tools match the two steps?', 'Glob for the filename pattern|Grep for references to the selected class|Write for the filename pattern|Edit for references|Bash deployment for both', 'AB', 'Glob finds paths; Grep searches file contents. The two-stage search narrows the codebase before reading implementation details.'),
      q('3.1', 'A new teammate does not receive the team’s SQL review rules, although the maintainer does. The rules are in ~/.claude/CLAUDE.md. What is the fix?', 'Move shared rules into version-controlled project instructions|Ask every teammate to copy the maintainer’s home directory|Increase context size only|Put the rules in a private terminal history', 'A', 'User-level CLAUDE.md is personal. Repository-scoped guidance is the mechanism for consistent team behavior.'),
      q('3.3', 'Repository tests live beside production files across dozens of packages. What rule scope applies the test convention everywhere but only to tests?', 'A .claude/rules/ glob such as **/*Test.java|A CLAUDE.md under one package|A global prompt for every file|An unrelated skill invoked manually', 'A', 'Path-scoped rules follow matching filenames across the tree and avoid loading test guidance when editing non-test files.'),
      q('3.4', 'Changing a single known assertion has a failing test and no design ambiguity. What mode is efficient?', 'Direct execution with verification|A broad architecture planning phase|A four-way fork before reading the test|An automated repository rewrite', 'A', 'The change is small and well located. Plan mode is useful when the architecture or scope must first be discovered.'),
      q('5.4', 'After a long exploration the assistant cites “typical bank patterns” instead of specific files it found. Which artifact helps recover grounded context?', 'A concise scratchpad with verified paths and relationships|More unfiltered terminal logs in chat|A prompt saying “remember everything”|A new unrelated model', 'A', 'A durable scratchpad keeps observed evidence available when conversational context degrades or is compacted.')
    ]),
    s('code-generation', 'Mobile SDK generator', 'A team uses Claude Code to maintain generated SDK clients for three languages. Repositories have shared conventions, language-specific rules, and a CI pipeline that checks generated code. Changes may span many packages.', [
      q('1.6', 'The generator changed 40 files. Local files look plausible, but imports across packages may break. Which review decomposition is best?', 'Per-file checks followed by a cross-package integration pass|One pass reading only the first file|A fixed five-turn chat regardless of results|No review because files were generated', 'A', 'Local checks catch file-level defects while an integration pass examines dependencies and contracts across package boundaries.'),
      q('1.7', 'Two candidate generator designs must be compared from the same discovery baseline. Which session operation fits?', 'Fork the analyzed session into independent branches|Append both experiments into one irreversible thread|Discard the baseline and start without notes|Resume one stale session twice sequentially', 'A', 'Forking creates independent explorations from shared context, allowing comparison without one design contaminating the other.'),
      q('2.5', 'A targeted Edit fails because the anchor string appears in 19 generated files. What is the reliable next step?', 'Read the intended file and use a unique surrounding anchor or deliberate full-file rewrite|Repeat the same ambiguous Edit|Use replace-all across all 19 generated files|Use Glob as a text replacement tool', 'A', 'Non-unique edits need narrower context or a deliberate rewrite of the exact file. Repeating an ambiguous patch risks the wrong target.'),
      q('3.1', 'The team has one root CLAUDE.md that has grown too large. Which TWO changes preserve shared guidance while reducing irrelevant context?', 'Move topic-specific rules into .claude/rules/|Use @import for maintained standards files|Move all shared instructions to one user’s home folder|Put every convention into one unscoped root file|Paste the full guide into every prompt', 'AB', 'Modular rule files and imports keep guidance maintainable and scoped. Personal files would break team consistency.'),
      q('3.2', 'A personal experimental /benchmark command should not affect teammates. Where should it be defined?', '~/.claude/commands/|Project .claude/commands/ committed to main|Root CLAUDE.md only|A generated source file', 'A', 'User-scoped commands remain personal. Project commands are version-controlled and intentionally shared.'),
      q('3.2', 'A skill that runs a verbose architecture comparison should avoid filling the primary conversation. Which frontmatter field is relevant?', 'context: fork|argument-hint only|A larger title|A duplicated system prompt', 'A', 'Forked skill context isolates lengthy exploration. An argument hint describes inputs but does not isolate output.'),
      q('3.3', 'Kotlin sources are spread under apps and libraries. Which rule pattern matches the language regardless of directory?', 'paths: ["**/*.kt"] in a .claude/rules/ file|A single rules file under apps only|A personal command run once|An unscoped root instruction for every language', 'A', 'A path glob scopes convention loading to Kotlin files across the repository, unlike a directory-local instruction.'),
      q('3.4', 'The team must choose between two client-generation libraries before a repository-wide rewrite. What is the first mode?', 'Plan mode for dependency and tradeoff analysis|Direct execution of all files immediately|A one-line find-and-replace|Skip evaluation because both libraries compile', 'A', 'Multiple viable architectural choices and broad edits justify a plan before writing. Compilation alone does not settle migration tradeoffs.'),
      q('3.5', 'Claude misinterprets how optional fields should serialize. Which input best refines the next iteration?', 'Two concrete input/output pairs, including a null edge case|“Be more careful”|A longer list of adjectives|A request for self-reported confidence', 'A', 'Concrete examples define observable serialization behavior and expose the ambiguous case directly.'),
      q('3.6', 'The CI generator must exit without interactive prompts and return machine-readable diagnostics. Which flags fit?', '-p with JSON output and a schema when needed|Interactive plan mode without a timeout|Only a natural-language final answer|A manual Enter key in every pipeline run', 'A', 'Print mode is non-interactive, while structured JSON output gives downstream automation a parseable contract.'),
      q('4.1', 'The generated SDK reviewer reports every naming difference even when output matches the spec. Which criterion improves precision?', 'Report only behavior or schema incompatibilities with evidence; skip harmless naming variance|Ask it to be generally conservative|Increase report length|Treat all differences as security bugs', 'A', 'A concrete exclusion boundary removes a predictable false-positive category instead of relying on vague caution.'),
      q('4.2', 'Reviews differ in how they describe breaking API changes. Which prompt addition most stabilizes format and judgment?', 'Two examples showing a true break and a harmless difference with exact output fields|A request to imitate its last answer|Only a maximum response length|A confidence score without examples', 'A', 'Paired positive and negative examples teach the decision boundary and the report schema simultaneously.'),
      q('4.6', 'The generator reviews its own output in the same session and misses a subtle serialization bug. Which TWO changes help?', 'Use a fresh independent review instance|Give it the actual generated diff and relevant tests|Ask the generator to restate its reasoning|Remove tests so review is faster|Ask the generating session for a longer self-review', 'AB', 'A fresh reviewer is less anchored to generation decisions; the concrete diff and tests supply evidence for independent inspection.'),
      q('4.6', 'A review of all generated languages at once loses cross-language parity findings. What two-pass plan fits?', 'Review each language locally, then compare shared API behavior across languages|Review only one language|Ask for a single enormous summary|Rerun the generator as reviewer', 'A', 'Local passes reduce attention dilution and an integration pass checks parity across language implementations.'),
      q('5.1', 'A resumed generator session remembers an old enum value and ignores the new specification. What must be refreshed?', 'A persistent current-spec facts block and affected source sections|Only the assistant’s tone|Every raw command ever run|The old enum explanation', 'A', 'Exact spec values should live in a current facts layer. A resumed or compacted history may preserve stale details unless changed inputs are reinjected.')
    ]),
    s('support', 'Travel booking disputes', 'A travel marketplace agent handles cancellations, credits, and itinerary errors. It can look up reservations and issue narrowly authorized credits. Some policy exceptions require staff approval, and customer identity must be verified before a financial action.', [
      q('1.1', 'Claude requests lookup_reservation, then returns a tool result request on the next iteration. When does the controller stop?', 'When a response has stop_reason end_turn|After the first tool result|Whenever an assistant text block appears|After an arbitrary number of turns as normal completion', 'A', 'The loop continues through tool requests and matching results until end_turn. Budgets are safety failures, not success criteria.'),
      q('1.1', 'The host app sends a tool result but omits the assistant message containing the original tool_use ID. What can go wrong?', 'The model loses the request/result correlation and conversation continuity|Nothing; tool results are standalone prompts|The result becomes a system instruction|The tool call is automatically replayed by GitHub', 'A', 'Tool results must follow the assistant tool_use content in the conversation so Claude can associate the result with the requested call.'),
      q('1.2', 'A cancellation case needs policy interpretation and reservation lookup, but no fraud specialist. How should the coordinator act?', 'Call only the needed specialists and synthesize their evidence|Run every specialist on every ticket|Let specialists send unaudited messages to each other|Send the whole customer history to every role', 'A', 'The coordinator should select specialists from the case requirements and control information flow, rather than paying for an irrelevant fixed pipeline.'),
      q('1.3', 'Policy and reservation specialists run concurrently. Which TWO facts must the coordinator provide to both?', 'The verified booking ID and issue summary|An assurance they inherit each other’s memory|Role-specific goals and permitted tools|An instruction to ignore source provenance|The final refund decision before investigation', 'AC', 'Parallel specialists need explicit shared case facts plus their separate task boundaries. They do not inherit each other’s context.'),
      q('1.4', 'A fare credit must never precede identity verification. Which control is sufficient as the enforcing boundary?', 'A pre-tool prerequisite gate keyed to verified identity|A bold sentence in the prompt only|A positive example in training data|A sentiment threshold', 'A', 'A deterministic pre-tool gate makes the rule enforceable even when the agent chooses an unsafe sequence.'),
      q('1.5', 'The credit tool returns policy codes 41 and 42, while reservation lookup returns human-readable statuses. What should happen before reasoning?', 'Normalize the tool outputs to a common named status vocabulary|Ask the user to interpret codes|Leave codes unexplained and rely on model guesses|Convert only the final customer message', 'A', 'A result normalization hook reduces ambiguity before the model compares records and policy conditions.'),
      q('1.7', 'A support case resumes after an agent changed the booking manually. Which context practice is safest?', 'Provide the change and refresh affected booking state|Trust the earlier lookup forever|Fork into an identical stale session|Summarize away the new status', 'A', 'Manual changes can invalidate prior tool evidence. A resumed session needs targeted re-analysis of the changed booking state.'),
      q('2.1', 'The model confuses find_itinerary with lookup_booking. What is the best description boundary?', 'Explain that one searches journey options and the other retrieves an existing booking by ID|Give both “find travel data”|Add a third identical tool|Force find_itinerary for all requests', 'A', 'Purpose and input distinctions reduce tool selection overlap. Generic wording causes the model to infer a boundary that is not documented.'),
      q('2.2', 'A credit is denied because the purchased fare is nonrefundable. How should the tool report it?', 'A non-retryable business error with a customer-readable reason|A transient service outage|An empty successful credit|The same request retried ten times', 'A', 'A policy denial needs a different path, not a retry. Structured business error metadata lets the agent explain or escalate.'),
      q('2.2', 'A reservation API times out while a different lookup returns “no reservation.” Which TWO distinctions matter?', 'Timeout is an access failure that may be retried|No reservation is a valid empty result when the query succeeded|Both should be reported as success with empty content|Both require a policy override|A timeout proves the booking does not exist', 'AB', 'A timeout gives no evidence of absence, while a successful empty query does. The coordinator needs different recovery decisions.'),
      q('2.3', 'The support role keeps invoking report-generation tools. Which correction is most direct?', 'Remove unrelated tools from the support role and provide a narrow handoff for reports|Add more report tools|Rename every tool to support_tool|Increase the context window only', 'A', 'Role-specific access reduces tool-choice confusion. A coordinator can request reporting when it is actually needed.'),
      q('4.2', 'Handoff summaries omit whether a credit was authorized or merely proposed. Which prompt change helps?', 'Examples contrasting approved and pending-credit handoffs with explicit status fields|A vague instruction to be clear|A larger model without examples|A self-grading confidence scale', 'A', 'Few-shot contrasts demonstrate the exact semantic distinction and output structure that prose guidance has failed to establish.'),
      q('5.1', 'A long chat contains booking date, traveler name, and a promised credit amount. What survives summarization?', 'A structured case-facts record with those exact values and source status|Only a sentiment score|Only the latest reply|A generic “customer has a problem” line', 'A', 'Persistent structured facts preserve dates, amounts, and identity while less relevant chat history is compressed.'),
      q('5.2', 'A traveler asks for a human because the written cancellation policy has no rule for a medical emergency. What should the agent do?', 'Escalate with the documented policy gap and evidence|Apply the closest existing exception without approval|Use negative sentiment alone as the reason|Retry the same policy lookup indefinitely', 'A', 'A genuine policy gap is an escalation trigger. Staff need the relevant policy text, booking facts, and the missing decision rule.'),
      q('5.2', 'Two travelers share a surname and the booking lookup returns both. What is the next safe action?', 'Request another identifier before financial action|Choose the first record|Choose the traveler with the higher fare|Make both records eligible for credit', 'A', 'Ambiguous identity needs clarification. A heuristic choice would risk applying a credit to the wrong account.')
    ]),
    s('extraction', 'Insurance claim intake', 'An insurer extracts incident dates, loss amounts, and supporting evidence from claim packets. Documents may be missing, multiple claim forms can conflict, and the nightly intake queue is latency-tolerant. Payout decisions remain a separate reviewed step.', [
      q('1.2', 'Some packets have only a form; others include photos and adjuster notes. What should an intake coordinator do?', 'Select analysis specialists based on the packet contents and aggregate evidence|Always invoke all available specialists|Ask the payout tool to analyze the packet|Treat every packet as a single image', 'A', 'Dynamic decomposition follows available evidence and avoids irrelevant specialist calls, while the coordinator preserves the final claim view.'),
      q('2.4', 'The team has a standard document-service MCP server and a proprietary claims database. What build/use choice is proportionate?', 'Reuse the maintained standard server and build only the claims-specific integration|Build every integration from scratch|Avoid MCP resources entirely|Commit database credentials with server config', 'A', 'Existing maintained integrations reduce ownership for standard services; a custom server is justified where proprietary workflow capability is missing.'),
      q('3.5', 'Claude repeatedly misreads handwritten deductible notation. Which iteration input is most useful?', 'Several labeled handwritten examples with expected normalized values and a failing test|A generic “try harder” request|A maximum-token increase only|A copy of unrelated invoices', 'A', 'Targeted examples and tests expose the exact interpretation failure and make the next result verifiable.'),
      q('3.6', 'A nightly Claude Code job generates tests for new extraction rules. What prevents repeat coverage suggestions?', 'Provide existing tests and fixture conventions in context|Hide the test directory|Run interactively and ask a developer to press Enter|Remove structured output', 'A', 'The model needs current test evidence and project conventions to identify genuine gaps rather than repeat existing cases.'),
      q('4.1', 'A review bot flags every unusual claim amount as fraud. Which criterion is more precise?', 'Flag only amounts that contradict explicit documents or validated rules, with cited evidence|Ask it to be conservative|Raise all flags to critical|Use sentiment as fraud evidence', 'A', 'Explicit evidence requirements distinguish unusual but valid values from reportable contradictions and reduce false positives.'),
      q('4.3', 'Each claim must fit one of three known schema types, but the type is unknown before extraction. Which tool_choice fits?', 'any with the three schema tools|auto if text answers are acceptable|Force the first schema for every packet|Disable tool use', 'A', 'any requires a structured tool call while leaving the schema choice to the model. auto could return free-form text.'),
      q('4.3', 'A police report is optional and sometimes absent. Which TWO schema choices reduce fabrication?', 'Allow null for report_number|Include an explicit evidence_status such as absent or unclear|Require a guessed report number|Remove all required fields|Replace schema validation with prose', 'AB', 'Representing absence and uncertainty in the contract is safer than requiring the model to invent a value that the packet does not contain.'),
      q('4.4', 'A schema-valid packet totals item losses at 12,400 but states 11,400. What should the application validate?', 'Arithmetic and source consistency, then pass the exact mismatch into a targeted retry or review|Only JSON syntax|Only word count|Only the model’s confidence', 'A', 'Structured output can still contain semantic errors. Deterministic checks identify the mismatch and provide actionable feedback.'),
      q('4.4', 'A missing repair estimate is not included in the packet. Why should identical retries stop?', 'The needed fact is absent from the provided source|JSON schemas cannot represent missing values|Retry unchanged until a nonempty value appears|Nightly work cannot ask for documents', 'A', 'A retry cannot recover unseen evidence. The pipeline should record the missing document and route the case appropriately.'),
      q('4.5', 'Ten thousand independent claim packets can complete by the next day. Which processing design fits?', 'Batch independent requests with custom_id correlation|Block each customer UI until the entire batch finishes|Use batch for a mid-request client-tool loop|Run only one document per night', 'A', 'A latency-tolerant bulk queue fits the Message Batches API, and custom_id is needed to reconcile responses to source packets.'),
      q('4.5', 'The nightly batch returns 43 failed packets, including two context-limit failures. Which TWO actions minimize rework?', 'Resubmit only failed custom_id items|Chunk the over-limit packets before resubmission|Resubmit all ten thousand unchanged|Treat failures as successful empty claims|Match failed responses by array position rather than custom_id', 'AB', 'Targeted resubmission preserves successful work, and over-limit documents need a modified representation rather than the same failing request.'),
      q('5.3', 'An OCR worker extracts pages 1–5, then cannot access page 6. What should it return?', 'An access error with partial fields, source pages, and retry attempts|A successful claim with page 6 guessed|A silent empty result|A generic failure without partial work', 'A', 'The coordinator can retain verified pages and decide how to recover only the missing page when error context and partial results are explicit.'),
      q('5.3', 'The coordinator receives “no police report” from one worker and “permission denied opening police report” from another. What distinction must it preserve?', 'Valid absence versus inaccessible evidence|Both mean the report does not exist|Both mean the claim is fraudulent|Both should trigger identical retries', 'A', 'A successful empty finding and a permission failure imply different confidence and recovery paths; collapsing them loses the evidence boundary.'),
      q('5.5', 'High-confidence fields are usually right but a new handwritten form has never been sampled. What should the review design add?', 'Stratified sampling of high-confidence items by form and field|Remove all human review immediately|Trust only aggregate accuracy|Use one universal confidence threshold without calibration', 'A', 'Stratified sampling tests unseen segments and detects novel errors that an overall high-confidence score can mask.'),
      q('5.6', 'Two claim forms disagree on the incident date. Which synthesis output is responsible?', 'Both dates with source locations and a conflict marker for review|The later date without attribution|The average date|An empty date with no explanation', 'A', 'Provenance and explicit conflict state preserve the evidence for an adjuster rather than hiding a disagreement in one chosen value.')
    ])
  ]);
})();
